/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 17:21:05 GMT 2019
 */

package edu.nju.vivofinal.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.nju.vivofinal.controller.TeacherIndexController;
import edu.nju.vivofinal.model.Teacher;
import edu.nju.vivofinal.service.TeacherInfoService;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;
import org.springframework.ui.Model;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TeacherIndexController_ESTest extends TeacherIndexController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn((HttpSession) null).when(httpServletRequest0).getSession(anyBoolean());
      Model model0 = mock(Model.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        teacherIndexController0.teacherInfo(httpServletRequest0, model0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.nju.vivofinal.controller.TeacherIndexController", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      HttpSession httpSession0 = mock(HttpSession.class, new ViolatedAssumptionAnswer());
      doReturn(teacherIndexController0).when(httpSession0).getAttribute(anyString());
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn(httpSession0).when(httpServletRequest0).getSession(anyBoolean());
      Model model0 = mock(Model.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        teacherIndexController0.teacherInfo(httpServletRequest0, model0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // edu.nju.vivofinal.controller.TeacherIndexController cannot be cast to java.lang.String
         //
         verifyException("edu.nju.vivofinal.controller.TeacherIndexController", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn((HttpSession) null).when(httpServletRequest0).getSession(anyBoolean());
      Model model0 = mock(Model.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        teacherIndexController0.teacherHome(httpServletRequest0, (HttpServletResponse) null, model0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.nju.vivofinal.controller.TeacherIndexController", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn((HttpSession) null).when(httpServletRequest0).getSession(anyBoolean());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      Model model0 = mock(Model.class, new ViolatedAssumptionAnswer());
      String string0 = teacherIndexController0.teacherHome(httpServletRequest0, httpServletResponse0, model0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      HttpSession httpSession0 = mock(HttpSession.class, new ViolatedAssumptionAnswer());
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn(httpSession0).when(httpServletRequest0).getSession(anyBoolean());
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      Model model0 = mock(Model.class, new ViolatedAssumptionAnswer());
      String string0 = teacherIndexController0.teacherHome(httpServletRequest0, httpServletResponse0, model0);
      assertNotNull(string0);
      assertEquals("teacher/teacher-home", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      Teacher teacher0 = mock(Teacher.class, new ViolatedAssumptionAnswer());
      doReturn((-466.17639851914265)).when(teacher0).getInfoCompleteDegree();
      doReturn("").when(teacher0).getTeacherPassword();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      doReturn(teacher0).when(teacherInfoService0).findTeacherInfoByMail(anyString());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      HttpSession httpSession0 = mock(HttpSession.class, new ViolatedAssumptionAnswer());
      doReturn("teacher/teacher-home").when(httpSession0).getAttribute(anyString());
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, new ViolatedAssumptionAnswer());
      doReturn(httpSession0).when(httpServletRequest0).getSession(anyBoolean());
      Model model0 = mock(Model.class, new ViolatedAssumptionAnswer());
      Model model1 = mock(Model.class, new ViolatedAssumptionAnswer());
      doReturn(model0, model0).when(model1).addAttribute(anyString() , any());
      String string0 = teacherIndexController0.teacherInfo(httpServletRequest0, model1);
      assertEquals("teacher/teacher-info", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      String string0 = teacherIndexController0.teacherCommonNotice();
      assertEquals("teacher/teacher-commonNotice", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      String string0 = teacherIndexController0.teacherStudents();
      assertEquals("teacher/teacher-students", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      String string0 = teacherIndexController0.teacherScoreNotice();
      assertEquals("teacher/teacher-scoreNotice", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      String string0 = teacherIndexController0.teacherStatistics();
      assertEquals("teacher/teacher-statistics", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TeacherIndexController teacherIndexController0 = new TeacherIndexController();
      TeacherInfoService teacherInfoService0 = mock(TeacherInfoService.class, new ViolatedAssumptionAnswer());
      Injector.inject(teacherIndexController0, (Class<?>) TeacherIndexController.class, "teacherInfoServiceImpl", (Object) teacherInfoService0);
      Injector.validateBean(teacherIndexController0, (Class<?>) TeacherIndexController.class);
      String string0 = teacherIndexController0.teacherNotice();
      assertEquals("teacher/teacher-notice", string0);
  }
}
