/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 17:18:27 GMT 2019
 */

package edu.nju.vivofinal.serviceimpl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.nju.vivofinal.serviceimpl.CommonServiceImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class CommonServiceImpl_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CommonServiceImpl commonServiceImpl0 = new CommonServiceImpl();
      String string0 = commonServiceImpl0.generateRandomCode(8);
      assertEquals(8, string0.length());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CommonServiceImpl commonServiceImpl0 = new CommonServiceImpl();
      String string0 = commonServiceImpl0.generateRandomCode(0);
      assertEquals("", string0);
  }

}
