/*
 * This file was automatically generated by EvoSuite
 * Mon May 27 06:06:31 GMT 2019
 */

package edu.nju.vivofinal.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.nju.vivofinal.controller.LoginIndexController;
import javax.servlet.http.HttpServletResponse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class LoginIndexController_ESTest{

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LoginIndexController loginIndexController0 = new LoginIndexController();
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, new ViolatedAssumptionAnswer());
      String string0 = loginIndexController0.login(httpServletResponse0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LoginIndexController loginIndexController0 = new LoginIndexController();
      // Undeclared exception!
      try { 
        loginIndexController0.login((HttpServletResponse) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.nju.vivofinal.controller.LoginIndexController", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LoginIndexController loginIndexController0 = new LoginIndexController();
      String string0 = loginIndexController0.teacherLogin();
      assertEquals("login/teacherLogin", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LoginIndexController loginIndexController0 = new LoginIndexController();
      String string0 = loginIndexController0.parentLogin();
      assertEquals("login/parentLogin", string0);
  }
}
