/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun May 26 17:22:02 GMT 2019
 */

package edu.nju.vivofinal;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class VIVOFinalApplication_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "edu.nju.vivofinal.VIVOFinalApplication"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "GBK"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\dell\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "CN"); 
    java.lang.System.setProperty("user.dir", "G:\\vivo\\VIVOFinal"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\dell"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "dell"); 
    java.lang.System.setProperty("user.timezone", ""); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(VIVOFinalApplication_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.util.ReflectionUtils$FieldFilter",
      "org.springframework.boot.devtools.restart.Restarter$LeakSafeThread",
      "org.springframework.aop.support.AopUtils",
      "org.springframework.boot.context.event.ApplicationReadyEvent",
      "org.springframework.cglib.core.ClassNameReader$EarlyExitException",
      "org.springframework.context.ApplicationContextException",
      "org.springframework.context.event.SimpleApplicationEventMulticaster",
      "org.springframework.context.event.AbstractApplicationEventMulticaster$ListenerRetriever",
      "org.springframework.boot.context.event.ApplicationStartedEvent",
      "org.springframework.context.ApplicationEventPublisher",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment$1",
      "org.springframework.boot.logging.logback.LogbackLoggingSystem",
      "org.springframework.core.io.Resource",
      "org.springframework.util.ClassUtils",
      "org.springframework.boot.devtools.restart.RestartInitializer",
      "org.springframework.core.annotation.AnnotationUtils",
      "org.springframework.util.StopWatch",
      "org.springframework.core.PriorityOrdered",
      "org.springframework.cglib.core.ClassNameReader",
      "org.springframework.context.support.AbstractApplicationContext",
      "org.springframework.boot.SpringApplicationRunListeners",
      "org.springframework.core.annotation.AnnotationAwareOrderComparator",
      "org.springframework.context.ApplicationContextAware",
      "org.springframework.core.Ordered",
      "org.springframework.core.env.CommandLinePropertySource",
      "org.springframework.util.ConcurrentReferenceHashMap$Entry",
      "org.springframework.boot.ApplicationArguments",
      "org.springframework.boot.context.config.DelegatingApplicationContextInitializer",
      "org.springframework.core.env.ConfigurablePropertyResolver",
      "org.springframework.util.ConcurrentReferenceHashMap$TaskOption",
      "org.springframework.core.ResolvableTypeProvider",
      "org.springframework.boot.devtools.restart.classloader.ClassLoaderFiles",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName",
      "org.springframework.beans.factory.BeanFactoryAware",
      "org.springframework.core.env.EnvironmentCapable",
      "org.springframework.boot.autoconfigure.BackgroundPreinitializer",
      "org.springframework.boot.context.ContextIdApplicationContextInitializer",
      "org.springframework.context.MessageSource",
      "org.springframework.boot.autoconfigure.EnableAutoConfiguration",
      "org.springframework.util.ConcurrentReferenceHashMap$Entries",
      "org.springframework.core.DecoratingProxy",
      "org.springframework.beans.BeansException",
      "org.springframework.context.annotation.ComponentScan",
      "org.springframework.boot.devtools.restart.MainMethod",
      "org.springframework.context.Lifecycle",
      "org.springframework.context.ApplicationEvent",
      "org.springframework.beans.factory.ObjectFactory",
      "org.springframework.boot.context.properties.source.InvalidConfigurationPropertyNameException",
      "org.springframework.core.ResolvableType$1",
      "org.springframework.beans.factory.BeanFactory",
      "org.springframework.boot.WebApplicationType",
      "org.springframework.boot.devtools.restart.SilentExitExceptionHandler",
      "org.springframework.boot.context.event.ApplicationPreparedEvent",
      "org.springframework.boot.devtools.restart.classloader.RestartClassLoader",
      "org.springframework.boot.devtools.restart.FailureHandler",
      "org.springframework.core.env.SimpleCommandLinePropertySource",
      "org.springframework.boot.SpringApplication",
      "org.springframework.core.io.support.PropertiesLoaderUtils",
      "org.springframework.boot.devtools.restart.Restarter",
      "org.springframework.context.ConfigurableApplicationContext",
      "org.springframework.context.event.ApplicationEventMulticaster",
      "org.springframework.boot.context.properties.bind.Bindable",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$ElementType",
      "org.springframework.aop.AopInvocationException",
      "org.springframework.core.NestedRuntimeException",
      "org.springframework.core.io.ResourceLoader",
      "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer",
      "org.springframework.cglib.core.ClassNameReader$1",
      "org.springframework.boot.ClearCachesApplicationListener",
      "org.springframework.core.env.Environment",
      "org.springframework.core.ResolvableType$VariableResolver",
      "org.springframework.boot.devtools.logger.DevToolsLogFactory$Listener",
      "org.springframework.boot.devtools.restart.classloader.ClassLoaderFileRepository",
      "org.springframework.util.ConcurrentReferenceHashMap$SoftEntryReference",
      "org.springframework.beans.BeanUtils",
      "org.springframework.beans.BeanInstantiationException",
      "org.springframework.core.io.UrlResource",
      "org.springframework.boot.logging.AbstractLoggingSystem$LogLevels",
      "org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer",
      "org.springframework.beans.factory.Aware",
      "org.springframework.beans.factory.config.Scope",
      "org.springframework.asm.ClassVisitor",
      "org.springframework.boot.builder.ParentContextCloserApplicationListener",
      "org.springframework.core.annotation.AnnotationUtils$AnnotationCacheKey",
      "org.springframework.aop.TargetClassAware",
      "org.springframework.context.event.AbstractApplicationEventMulticaster$ListenerCacheKey",
      "org.springframework.boot.logging.Slf4JLoggingSystem",
      "edu.nju.vivofinal.VIVOFinalApplication",
      "org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener",
      "org.springframework.context.event.ApplicationContextEvent",
      "org.springframework.context.event.GenericApplicationListener",
      "org.springframework.core.annotation.AliasFor",
      "org.springframework.boot.logging.logback.LogbackLoggingSystem$1",
      "org.springframework.beans.FatalBeanException",
      "org.springframework.core.ResolvableType$DefaultVariableResolver",
      "org.springframework.boot.SpringApplicationRunListener",
      "org.springframework.context.support.GenericApplicationContext",
      "org.springframework.core.SerializableTypeWrapper",
      "org.springframework.core.ResolvableType$TypeVariablesVariableResolver",
      "org.springframework.context.event.ContextRefreshedEvent",
      "org.springframework.util.ReflectionUtils",
      "org.springframework.core.io.support.ResourcePatternResolver",
      "org.springframework.context.ApplicationContextInitializer",
      "org.springframework.util.Assert",
      "org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener",
      "org.springframework.boot.devtools.restart.RestartScopeInitializer",
      "org.springframework.util.ErrorHandler",
      "org.springframework.core.env.PropertyResolver",
      "org.springframework.aop.framework.AopProxyUtils",
      "org.springframework.core.io.support.SpringFactoriesLoader",
      "org.springframework.boot.context.event.ApplicationContextInitializedEvent",
      "org.springframework.core.annotation.AnnotationConfigurationException",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$ElementsParser",
      "org.springframework.boot.context.event.ApplicationStartingEvent",
      "org.springframework.core.env.CompositePropertySource",
      "org.springframework.boot.logging.LoggerConfigurationComparator",
      "org.springframework.boot.devtools.restart.RestartApplicationListener",
      "org.springframework.util.CollectionUtils",
      "org.springframework.core.io.InputStreamSource",
      "org.springframework.boot.devtools.restart.SilentExitExceptionHandler$SilentExitException",
      "org.springframework.util.ConcurrentReferenceHashMap$Task",
      "org.springframework.beans.factory.ListableBeanFactory",
      "org.springframework.core.env.PropertySource",
      "org.springframework.context.event.GenericApplicationListenerAdapter",
      "org.springframework.aop.framework.Advised",
      "org.springframework.core.env.EnumerablePropertySource",
      "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager",
      "org.springframework.context.event.ContextClosedEvent",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "org.springframework.core.KotlinDetector",
      "org.springframework.boot.context.event.ApplicationEnvironmentPreparedEvent",
      "org.springframework.core.env.ConfigurableEnvironment",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$Elements",
      "org.springframework.boot.context.FileEncodingApplicationListener",
      "org.springframework.core.ResolvableType$EmptyType",
      "org.springframework.util.ConcurrentReferenceHashMap$1",
      "org.springframework.util.ConcurrentReferenceHashMap$2",
      "org.springframework.util.ConcurrentReferenceHashMap$3",
      "org.springframework.boot.autoconfigure.SpringBootApplication",
      "org.springframework.util.ConcurrentReferenceHashMap$4",
      "org.springframework.aop.SpringProxy",
      "org.springframework.boot.ExitCodeEvent",
      "org.springframework.context.event.SmartApplicationListener",
      "org.springframework.beans.factory.config.BeanFactoryPostProcessor",
      "org.springframework.util.ObjectUtils",
      "org.springframework.boot.logging.logback.SpringBootJoranConfigurator",
      "org.springframework.util.MultiValueMap",
      "org.springframework.boot.logging.LogLevel",
      "org.springframework.core.OrderComparator",
      "org.springframework.util.ResourceUtils",
      "org.springframework.util.ReflectionUtils$MethodFilter",
      "org.springframework.boot.SpringBootConfiguration",
      "org.springframework.util.ConcurrentReferenceHashMap$5",
      "org.springframework.util.LinkedMultiValueMap",
      "org.springframework.boot.devtools.restart.AgentReloader",
      "org.springframework.beans.factory.HierarchicalBeanFactory",
      "org.springframework.boot.logging.LoggingSystem$NoOpLoggingSystem",
      "org.springframework.util.ConcurrentReferenceHashMap$Reference",
      "org.springframework.boot.context.config.DelegatingApplicationListener",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "org.springframework.boot.Banner$Mode",
      "org.springframework.beans.factory.support.BeanDefinitionRegistry",
      "org.springframework.boot.context.config.AnsiOutputApplicationListener",
      "org.springframework.core.ResolvableType$SyntheticParameterizedType",
      "org.springframework.boot.logging.DeferredLog",
      "org.springframework.boot.context.event.EventPublishingRunListener",
      "org.springframework.core.ResolvableType",
      "org.springframework.core.annotation.SynthesizedAnnotation",
      "org.springframework.boot.env.EnvironmentPostProcessor",
      "org.springframework.web.context.WebApplicationContext",
      "org.springframework.context.ApplicationListener",
      "org.springframework.boot.context.event.ApplicationFailedEvent",
      "org.springframework.core.AliasRegistry",
      "org.springframework.core.SmartClassLoader",
      "org.springframework.util.PropertiesPersister",
      "org.springframework.core.annotation.AnnotationAttributeExtractor",
      "org.springframework.core.SerializableTypeWrapper$TypeProvider",
      "org.springframework.core.env.MapPropertySource",
      "org.springframework.util.ConcurrentReferenceHashMap$Restructure",
      "org.springframework.beans.factory.BeanClassLoaderAware",
      "org.springframework.core.annotation.OrderUtils",
      "org.springframework.boot.context.logging.LoggingApplicationListener",
      "org.springframework.core.ResolvableType$WildcardBounds",
      "org.springframework.boot.logging.LoggingSystem",
      "org.springframework.context.event.AbstractApplicationEventMulticaster",
      "org.springframework.boot.devtools.restart.DefaultRestartInitializer",
      "org.springframework.core.io.AbstractFileResolvingResource",
      "org.springframework.core.io.DefaultResourceLoader",
      "org.springframework.core.annotation.AnnotationUtils$AliasDescriptor",
      "org.springframework.core.SerializableTypeWrapper$SerializableTypeProxy",
      "org.springframework.boot.context.config.ConfigFileApplicationListener",
      "org.springframework.boot.context.logging.ClasspathLoggingApplicationListener",
      "org.springframework.core.annotation.Order",
      "org.springframework.boot.builder.ParentContextApplicationContextInitializer$ParentContextAvailableEvent",
      "org.springframework.core.NestedIOException",
      "org.springframework.context.ApplicationContext",
      "org.springframework.web.context.ConfigurableWebApplicationContext",
      "org.springframework.core.io.AbstractResource",
      "org.springframework.boot.context.event.SpringApplicationEvent",
      "org.springframework.beans.factory.NoSuchBeanDefinitionException",
      "org.springframework.boot.logging.DeferredLog$Line",
      "org.springframework.boot.logging.AbstractLoggingSystem",
      "org.springframework.util.StringUtils"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(VIVOFinalApplication_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "edu.nju.vivofinal.VIVOFinalApplication",
      "org.springframework.boot.SpringApplication",
      "org.springframework.boot.Banner$Mode",
      "org.springframework.util.Assert",
      "org.springframework.boot.WebApplicationType",
      "org.springframework.util.ClassUtils",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceType",
      "org.springframework.util.ConcurrentReferenceHashMap",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment",
      "org.springframework.util.ConcurrentReferenceHashMap$ReferenceManager",
      "org.springframework.core.io.support.SpringFactoriesLoader",
      "org.springframework.util.ConcurrentReferenceHashMap$Restructure",
      "org.springframework.util.LinkedMultiValueMap",
      "org.springframework.core.io.AbstractResource",
      "org.springframework.core.io.AbstractFileResolvingResource",
      "org.springframework.core.io.UrlResource",
      "org.springframework.util.StringUtils",
      "org.springframework.util.CollectionUtils",
      "org.springframework.core.io.support.PropertiesLoaderUtils",
      "org.springframework.util.ResourceUtils",
      "org.springframework.util.ConcurrentReferenceHashMap$Task",
      "org.springframework.util.ConcurrentReferenceHashMap$1",
      "org.springframework.util.ConcurrentReferenceHashMap$TaskOption",
      "org.springframework.util.ConcurrentReferenceHashMap$Entries",
      "org.springframework.util.ConcurrentReferenceHashMap$Segment$1",
      "org.springframework.util.ConcurrentReferenceHashMap$Entry",
      "org.springframework.util.ConcurrentReferenceHashMap$SoftEntryReference",
      "org.springframework.beans.BeanUtils",
      "org.springframework.util.ReflectionUtils",
      "org.springframework.core.KotlinDetector",
      "org.springframework.boot.context.ConfigurationWarningsApplicationContextInitializer",
      "org.springframework.boot.context.ContextIdApplicationContextInitializer",
      "org.springframework.boot.context.config.DelegatingApplicationContextInitializer",
      "org.springframework.boot.web.context.ServerPortInfoApplicationContextInitializer",
      "org.springframework.boot.autoconfigure.SharedMetadataReaderFactoryContextInitializer",
      "org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener",
      "org.springframework.boot.logging.LogLevel",
      "org.springframework.boot.devtools.restart.RestartScopeInitializer",
      "org.springframework.core.OrderComparator",
      "org.springframework.core.annotation.AnnotationAwareOrderComparator",
      "org.springframework.core.annotation.OrderUtils",
      "org.springframework.core.annotation.AnnotationUtils",
      "org.springframework.core.annotation.AnnotationUtils$AnnotationCacheKey",
      "org.springframework.util.ObjectUtils",
      "org.springframework.boot.ClearCachesApplicationListener",
      "org.springframework.boot.builder.ParentContextCloserApplicationListener",
      "org.springframework.boot.context.FileEncodingApplicationListener",
      "org.springframework.boot.context.config.AnsiOutputApplicationListener",
      "org.springframework.boot.context.properties.bind.Bindable",
      "org.springframework.core.ResolvableType$EmptyType",
      "org.springframework.core.ResolvableType",
      "org.springframework.boot.context.config.ConfigFileApplicationListener",
      "org.springframework.boot.logging.DeferredLog",
      "org.springframework.boot.context.config.DelegatingApplicationListener",
      "org.springframework.boot.context.logging.ClasspathLoggingApplicationListener",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$Elements",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$ElementsParser",
      "org.springframework.boot.context.properties.source.ConfigurationPropertyName$ElementType",
      "org.springframework.core.SerializableTypeWrapper",
      "org.springframework.core.ResolvableType$SyntheticParameterizedType",
      "org.springframework.core.ResolvableType$TypeVariablesVariableResolver",
      "org.springframework.boot.context.logging.LoggingApplicationListener",
      "org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener",
      "org.springframework.boot.autoconfigure.BackgroundPreinitializer",
      "org.springframework.boot.devtools.restart.RestartApplicationListener",
      "org.springframework.boot.devtools.logger.DevToolsLogFactory$Listener",
      "org.springframework.core.annotation.AnnotationUtils$AliasDescriptor",
      "org.springframework.util.StopWatch",
      "org.springframework.boot.SpringApplicationRunListeners",
      "org.springframework.boot.context.event.EventPublishingRunListener",
      "org.springframework.context.event.AbstractApplicationEventMulticaster",
      "org.springframework.context.event.SimpleApplicationEventMulticaster",
      "org.springframework.context.event.AbstractApplicationEventMulticaster$ListenerRetriever",
      "org.springframework.aop.framework.AopProxyUtils",
      "org.springframework.context.ApplicationEvent",
      "org.springframework.boot.context.event.SpringApplicationEvent",
      "org.springframework.boot.context.event.ApplicationStartingEvent",
      "org.springframework.context.event.AbstractApplicationEventMulticaster$ListenerCacheKey",
      "org.springframework.context.event.GenericApplicationListenerAdapter",
      "org.springframework.core.ResolvableType$DefaultVariableResolver",
      "org.springframework.core.ResolvableType$WildcardBounds",
      "org.springframework.aop.support.AopUtils",
      "org.springframework.boot.devtools.restart.DefaultRestartInitializer",
      "org.springframework.boot.devtools.restart.AgentReloader",
      "org.springframework.boot.devtools.restart.Restarter",
      "org.springframework.boot.devtools.restart.classloader.ClassLoaderFiles",
      "org.springframework.boot.logging.DeferredLog$Line",
      "org.springframework.boot.devtools.restart.SilentExitExceptionHandler",
      "org.springframework.boot.devtools.restart.MainMethod",
      "org.springframework.boot.devtools.restart.Restarter$LeakSafeThread",
      "org.springframework.cglib.core.ClassNameReader$EarlyExitException",
      "org.springframework.cglib.core.ClassNameReader",
      "org.springframework.boot.logging.LoggingSystem",
      "org.springframework.boot.logging.LoggerConfigurationComparator",
      "org.springframework.boot.logging.AbstractLoggingSystem",
      "org.springframework.boot.logging.Slf4JLoggingSystem",
      "org.springframework.boot.logging.AbstractLoggingSystem$LogLevels",
      "org.springframework.boot.logging.logback.LogbackLoggingSystem$1",
      "org.springframework.boot.logging.logback.LogbackLoggingSystem"
    );
  }
}
