/*
 * This file was automatically generated by EvoSuite
 * Sun May 26 16:59:18 GMT 2019
 */

package edu.nju.vivofinal.daoimpl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.nju.vivofinal.daoimpl.BaseDaoImpl;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

@RunWith(SpringRunner.class)
@SpringBootTest
public class BaseDaoImpl_ESTest{



  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      BaseDaoImpl baseDaoImpl0 = new BaseDaoImpl();
      // Undeclared exception!
      try { 
        baseDaoImpl0.getSession();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("edu.nju.vivofinal.daoimpl.BaseDaoImpl", e);
      }
  }


}
